apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
      - name: nginx
        image: soumya081693/mysql:1.0.0
---
kind: Service
apiVersion: v1
metadata: 
  name: mysql
spec:
  selector: #labels re used as selectors
    app: mysql
    tier: mysql
    project: expense
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306
